[package]
name = "doc"
version = "0.1.0"
authors = ["shubham.asati2626@gmail.com <webdeveloper@netmobix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
